id: IFEBFB82B
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-06-17T13:57:50.981328'
last_modified: '2022-06-17T13:57:50.981352'
parser: null
source_metadata:
  title: Sakya Series
  language: bo
  description: 'Texts related to the Sakya (sa skya) tradition and its sub-branches:'
  volume:
    f265B:
      title: 'Sweet Nectar of the Supreme Vehicle: A Synopsis of the Stages of the
        Mahāyāna Path'
      base_file: f265B.txt
      order: 1
      parent: Advice
    fD73E:
      title: 'The Pellucid Mirror: Behavioural Guidelines for the Saṅgha'
      base_file: fD73E.txt
      order: 2
      parent: Behavioural Guidelines
    fE0EE:
      title: Notice on Behalf of Sejo Monastery in Dzakhok
      base_file: fE0EE.txt
      order: 3
      parent: Letters
    fFB2E:
      title: Supplement to the Omniscient Ngorchen Kunga Zangpo’s Prayer to the Lineage
        of Parting from the Four Attachments
      base_file: fFB2E.txt
      order: 4
      parent: Lineage Prayers
    fD25B:
      title: Prayer to the Lineage of Parting from the Four Attachments
      base_file: fD25B.txt
      order: 5
      parent: Lineage Prayers
    f214F:
      title: Aspiration to Follow the Gurus of the Ngor Tradition
      base_file: f214F.txt
      order: 6
      parent: Prayers
    fC4F5:
      title: Prayer to the Supremely Learned Holders of the Glorious Sakya Teachings
      base_file: fC4F5.txt
      order: 7
      parent: Prayers
    f2948:
      title: Prayer to Root and Lineage Masters, and the Assembly of Deity, Ḍākinīs
        and Dharma Protectors of the Sakya Lineage
      base_file: f2948.txt
      order: 8
      parent: Prayers
    f44A0:
      title: 'Divine Music: Words of Encouragement for the Authentic Path'
      base_file: f44A0.txt
      order: 9
      parent: Songs
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
